Backend/routes/users/login.js

I have added the expiration time of the JWT token to 15minutes.
Fixes #19 
- [] I have made corresponding changes to the documentation

Added Expiration time to JWT token.

---

Backend/routes/EventRoutes.js

Added Delete Route in /event/:title
Fixes #18 

Delete Route Added

---

Frontend/index.html
Frontend/style.css

Fixed the footer to bottom of the screen
Changed the UI of Cards 

Responsiveness and footer fixed to bottom

---

Frontend/data/events.json

Add new event to events.json file

add new event to events.json file

---

Backend/package-lock.json
Backend/package.json
Backend/routes/EventRoutes.js
Backend/routes/users/auth.js
Backend/routes/users/logout.js
Backend/server.js
Backend/services/cacheService.js

Logout route is created and tested to be working.
It uses a blocklist approach in which the blocklist is stored in the cache memory and is checked with for every protected API call.
New dependencies are added:
- node-cache
- shortid
Fixes #29 

feat(logout): add logout route

---

Frontend/data/events.json

A new event FOSDEM 2021 added to events.json file.
- [1] My code follows the style guidelines of this project
- [1] I have performed a self-review of my own code
- [1] My changes generate no new warnings

New event FOSDEM added

---

Frontend/style.css

Fixed the transition on hovering the cards .
Fixes 
Uneven transition on hovering and removing hover.
CSS

hover transition fixed

---

Frontend/js/getEvent.js
index.html

I have added a **search bar** in the **foss-events application** where user can easily search for a specific event and not waste his time looking for it in the whole application.
Fixes #41 
My code follows the style guidelines of this project

Search bar added

---

Backend/routes/EventRoutes.js

Existing Event (test2)          |  After Update Event
:-------------------------:|:-------------------------:
* It will update the event if exists
* It will return error message if event not found

Added Event Update Route

---

Frontend/data/events.json

Added a new Open Source event in the /Frontend/data/events.json file.
Event name: FOSSCOMM

Added FOSSCOMM event in event.js

---

Frontend/data/events.json

Added Devfest India to `events.json` file.

Added DevFest India to events.json

---

Frontend/data/events.json

Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Added event All Things Open

---

Frontend/data/events.json

Added new event to events.json file in Frontend.

Added new event to events.json

---

Frontend/data/events.json

Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.

first commit

---

Frontend/data/events.json

Updated events.json by adding two events,
1)MLH Fellowship
2)Outreachy
And fixed the links of the GSOC and the GSSOC

Updated events.json, Added two events and fixed the links of GSSOC and GSOC 

---

Frontend/data/events.json

I have added two events as the issue demands.
1. BOSS - Bountiful Open Source Summer (2021)
2. 24 Pull Requests (2021)
Fixes # (86)

Added the Events

---

Frontend/data/events.json
Frontend/js/getEvent.js
Frontend/style.css
index.html

1)Updated events.json
2)Fixed broken links of
i)BOSS
ii)24 Pull Requests
3) Added Light - Dark Mode
4) Fixed the Right padding of cards

Updated events.json , Fixed the broken links in events.json , Added Light - Dark Mode, Fixed the right padding of cards 

---

Frontend/js/getEvent.js
Frontend/style.css

I have added offline status to those evet cards whose end date has gone.
Added red color to the event status if it is offline.
Fixes # (164)
I have changed two files:
style.css
getEvent.js

Added offline status to event cards whose end date is gone

---

Frontend/style.css

I made the navbar sticky/fixed while scrolling down the page.
Fixes #177 
https://user-images.githubusercontent.com/61618767/111783568-58468300-88e0-11eb-9abd-d70bb5c95187.mp4

Made Navbar Sticky

---

Frontend/data/events.json

it is working fine now 
Thank you

no event on landing page issue solved now

---

Frontend/style.css

I have added the box shadow feature for the card, Initially particular event card will be having some shadow, On hovering, as the card moves back the shadow also kind of disappear.
Fixes #179 
I have changed one file: style.css

Added card shadow feature

---

Frontend/data/events.json

Updated the events.json file by adding information about Processing foundation Fellowship Program

fixed issue 150

---

BEST_PRACTICES.md

With reference to issue #138 
Added BEST_PRACTICES.md

add BEST_PRACTICES.md

---

Frontend/style.css

I redesign and customized the Scrollbar.
Fixes https://github.com/DSC-JSS-NOIDA/foss-events/issues/185 (issue)
style.css

customized and redesign scrollbar

---

Frontend/js/getEvent.js
Frontend/style.css
index.html

I have added the Scroll to top button 
Fixes Scroll to Top button on the home page #190

Scroll to top button added

---

Frontend/style.css

I have added the hover effect on more info button inside the card.
Fixes #199 
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] Any dependent changes have been merged and published in downstream modules

More Info button Hover effect

---

Frontend/data/events.json
Frontend/js/getEvent.js
index.html

There were some issues with the previous PR #189 so, I'm again submitting a PR after removing the conflicts.
In this filter, we can introduce a left bound and a right bound and then we can selectively get all those events whose tenure lies between the specified range of dates!
Fixes #170 (issue)
https://user-images.githubusercontent.com/61948033/112051952-86de8b00-8b78-11eb-841c-202c6d86fa1d.mp4

Putting another pull request referring to PR #189

---

Frontend/js/getEvent.js
Frontend/style.css
index.html

Added the event status filter. Online and Offline event can be filtered. 
Fixes #217

Add event status filter

---

Frontend/data/events.json
Frontend/js/getEvent.js
Frontend/style.css
index.html

Added the Contact us section and social media icons at the bottom of the page.
Fixed the Dark mode UI.
Added two events,
1)Alibaba Summer of Code
2)ERPNEXT Summer of Code
In Light mode,
===
===
In Dark mode,
===
===

Added Contact Us section and Social media Icons, Fixed Dark mode UI, Added Events in events.json

---

Frontend/style.css

Issue Number #192 
Fixed dark mode issue.
Original
Updated

Fixed Issue Number #192 (Problem in dark mode section in the website)

---

Backend/db/db.js

Fixes #233 
Added mongoose event listeners for connected, reconnected, error thrown, disconnected and app termination.
Requires no extra dependencies

added mongoose event listeners

---

index.html

Used <a> tag to make links clickable.
Issue Number #234 

Fixed Issue Number #234 (Adding functional links in contact us section )

---

Frontend/style.css
index.html

I had added a search icon in the search box which makes it more appealing and interactive for the users.
Fixes #242 
###Before:
###After:
Hope everything is clear.
Thanks.

feat:Added Search icon-issue-#242

---

Frontend/data/events.json

The 5 events are,
1)Digital Ocean Hacktoberfest
2)Season of KDE
3)Open Mainframe Project Mentorship Program
4)Linux Kernel Mentorship Program
5)Redox OS Summer of Code
It solves issue #235

Adding 5 events in events.json

---

index.html

Please include a summary of the change and which issue is fixed. 
Clicking on location and mail in contact us section, now user can be direclty prompted to the desired destination.
Please also include relevant motivation and context. 
Making the project user friendly.
#228 
Inserted desired links.

Added required links to Mail and Location in Contact Us

---

Frontend/js/getEvent.js
Frontend/style.css
index.html
package-lock.json

Enhanced the Style of toggle button and Added simple and subtle Animations to toggle Button Only Ussing Css makes Site code much lighter due to Deletion of unwanted Lines if HTML and CSS code.
and 
Fixes # 227
Four ScreenShots Added Comparing between older and New UI

Enhanced the toggle style on issue #227

---

Frontend/style.css

changes the appearance of title and make it responsive to event card
Fixes #215  (issue)
please delete options that are not relevant.

 changes in appearence of title

---

index.html

Changed the placeholder text of the search bar

---

index.html

Reverts DSC-JSS-NOIDA/foss-events#221

Revert "Changed the placeholder text of the search bar"

---

index.html

Fixed the search bar, and made the text more appropriate

---

Frontend/style.css
index.html

Now, whenever we hover on the contact, email or phone number, we will get a hover effect and its clickable for fast communication

Improved the social section

---

Frontend/js/getEvent.js
Frontend/style.css
index.html

Added the suggestion box of the names of the events under the search input tag. When anyone wants to search any event, then it will give some suggestions according to users' initial input.
In dark mode,
In light mode,
Also added the working video of the same,
https://user-images.githubusercontent.com/75881393/112895284-886cfd80-90fa-11eb-8ec4-a7a0bfbd9177.mp4

Added Dropdown events in search input tag

---

Frontend/data/events.json

Added 6 events to the list of events in events.json.

Adding events in events.json

---

Frontend/style.css
index.html

Added preloader scripts and css.
Issue #229 
Added smooth transition in toggle button

Issue #229

---

Frontend/style.css
index.html

Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
Fixes #265 
Before:
After:

fix : Content Aligned Properly

---

Frontend/style.css
index.html

Added an "About us" section, which describes the website in more detailed manner. Also I've modified the navbar(which are clickable). I've done it in such a way that it also work properly in the dark mode. Cheers.

Added "About us" section and modified the navbar.

---

Frontend/data/events.json
index.html

This pull request : 
Fixes #282 
Adds two open source programs to the list, NWOC and KWOC
Fixes #283 
Updates the website description a bit and includes the word program in place of organization

Fixes #282 and #283

---

Frontend/js/getEvent.js
Frontend/style.css

I have added a message for those search results if there is no event related to that range in date.
Fixes #291
Original:
Updated;

Message for no search result added

---

Frontend/js/getEvent.js

When no event matched with search query, message displayed "Sorry! no event to display"
Fixes # 294

All display messages of  search results modified

---

Frontend/style.css

@AkshaySharma008 please review it

resolved the text collision with search bar in mobile mode

---

Frontend/style.css

added responsivness to the website
The fonts and the event card size was not appropriate for mobile view,
so I changed font sizes and make them responsive in the navbar, events and contact section
also i have increased the width of event card in mobile view and removed extra margin of paragraph in mobile view
Fixes #303 
- [] I have made corresponding changes to the documentation
- [] Any dependent changes have been merged and published in downstream modules
before
after
before
after

added responsivness to the website

---

Frontend/style.css

Reverts DSC-JSS-NOIDA/foss-events#313

Revert "added responsivness to the website"

---

Frontend/style.css
index.html

Make a minor change to CSS and the loading animation start working as expected. 
Fixes #315 
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] Design fix
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings

Loading Animation Issue Solved.

---

index.html

I have made autocomplete off to the input field of contact us section
Fixes #296

autocomplete made off

---

Frontend/style.css
index.html

I made the color of the label black as it was previously in white color and not visible properly in the dark mode.
Fixes #320 

dark labels added in dark mode

---

Frontend/style.css
index.html

I removed the size of the text that increases while hovering.
Fixes #297

While hovering over the cards it scales out much #297

---

Frontend/style.css

I have changed the background of scroll tracker bar from transparent to Navbar color. It is looking perfectly fine.
I also want to change hover state of event.title because it is so fast , if we make transition 0.2s ease-in-out it is looking smooth
Fixes #280  (issue)
@AkshaySharma008 
#280 

Bug Fixed - Scroll Bar background 

---

Frontend/style.css

Footer text not visible in dark mode
Fixes #172 
Added red color to the text since it will attract the user to see the footer text, also red color works fine with light and dark mode.

added red color to the footer text againt issue #172

---

Frontend/style.css
index.html

I have added social media icons to left of the page.
Fixes #319 
https://user-images.githubusercontent.com/75009990/115587852-c15c5480-a2eb-11eb-8bd2-7a02e31ef573.mp4

social media icons added

---

Frontend/style.css

Changed the color of  "Made with ❤ By" in the footer such that it looks fine both in light and dark mode.
Earlier it wasn't visible in dark mode due to its color.
Fixes [#330](https://github.com/DSC-JSS-NOIDA/foss-events/issues/330)

footer: color of "Made with ❤ By" changed

---

Frontend/style.css

- Changed color of navbar to green.
- Changed the colors of toggle button for dark theme so that it looks fine with the green color of navbar.
Fixes #328

improved colors in navbar

---

Frontend/style.css

Changed the color of "Made with ❤ By" in footer to grey instead of red.
Fixes #330 

changed footer text color

---

Frontend/style.css
index.html

Improved the Search Bar by:
- Making the icons visible in dark mode.
- Added background gradient to the bar that matches with the theme.
- Improved the positioning of the bar.

Improved Search Bar

---

Frontend/style.css

Fixed the search bar to make it responsive.

Made the search bar responsive.

---

Frontend/data/events.json

Fixes #344 
I have added a new FOSS event: Hyperledger Mentorship Program.

Added Hyperledger Mentorship Program

---

Frontend/data/events.json

Adding More Open Source Events

---

README.md

Updated the README.md in the integration branch,
Its screenshots,

Update README.md for the Integration branch

---

index.html

The search icon was not showing, so I have added a search icon.
Fixes #358 

fixes search icon

---

Frontend/js/getEvent.js
Frontend/style.css

Message is displayed when message is submitted successfully.
Fixes #318

Message displayed

---

index.html

I have added validations if user submit contact us form without any entry.
Fixes #338 

Validation added

---

.eslintrc.js
package.json

Done ESlint setup and linting the code and making it prettier
Made modifications and enhancements in package.json and made .eslintrc.json file in parent folder
Fixes #370

added eslint setup and prettier code

---

index.html

I have added a time clock in the website to make easy usage and more feasibility.
Fixes #374

Update index. html by adding clock

---

Frontend/style.css
index.html

I have added the following social links:
Website: https://www.dscjss.in/
Medium: https://medium.com/dsc-jss-noida
YouTube: https://www.youtube.com/channel/UCkELk5JFDceaSf8pBa19kDQ
Fixes #359

Added 3 Social Links

---

Frontend/style.css
index.html

#391 
I have give some hover effect on the event card.

hover effect on event card

---

Frontend/style.css
index.html

Reverts DSC-JSS-NOIDA/foss-events#392

Revert "hover effect on event card"

---

Frontend/data/events.json

Added information about osoc program in events.json file.
Fixes #398

completed issue 398

---

Backend/.env.example
Backend/package-lock.json
Backend/package.json
Backend/routes/users/getreq.js
Backend/routes/users/signup.js
Backend/server.js

Live at Render with new MongoDB Database

Backend updated
